### ISSUE TITLE
None of the available transfter mode swork 

### ISSUE THREAD

**Issue by posbank2** [SamKirkland/FTP-Deploy-Action#229]
on: push
name: Deploy website on push 1
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server:  myhostname 
        username: username 
        password: password 
        server-dir : www/ 

1 set up job ok 
2.Get latest code ok 
3. sync files  error 
📁 Create: admin
➕ Upload: admin/404.html
➕ Upload: admin/blank.html
➕ Upload: admin/buttons.html
➕ Upload: admin/cards.html
➕ Upload: admin/charts.html
📁 Create: admin/ckeditor
10867 uploading "admin/404.html" 

Error: None of the available transfer modes work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3494:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Error: None of the available transfer modes work.

All firewalls allow port 21.
The file transfer is interrupted.

Its file permissions are the same as all other files.
Could a lot of files be a problem?

I keep getting an error from a specific file.

**Comment by emyu01** [comment]
Having same issue

**Comment by manuelescrig** [comment]
Same issue for me.

**Comment by bertugmete** [comment]
Same issue :(

**Comment by emyu01** [comment]
Downgrading to v4.0.0 solved the issue for me

**Comment by GaelCodes** [comment]
I had the same issue, make sure ports for data channel are open.
You need to open port for command channel, but also for the range of ports that you specified to your ftp server to use when passive mode is requested.

It works for me.

**Comment by kingyue737** [comment]
I've located the issue! The problem is that 127.0.0.1 is not considered as private address:

https://github.com/patrickjuchli/basic-ftp/blob/e1acee0215bf8e39c490a470e98cdaa0898460b3/src/netUtils.ts#L55

**Comment by patrickjuchli** [comment]
@SamKirkland, this should be fixed with basic-ftp 5.0.0.

**Comment by SamKirkland** [comment]
@patrickjuchli you rock! ♥️🚀
I'll upgrade asap

**Comment by mhasanmeet** [comment]
```
Error: None of the available transfer modes work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4323:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Error: None of the available transfer modes work.
```

This issue happens. Can you please solve the issue? Thank you so much for your contributing time, sir.

**Comment by KimpShreyan** [comment]
Error: None of the available transfer modes work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.2/dist/index.js:4803:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by harry2712** [comment]
i also get the same
Error: None of the available transfer modes work.

**Comment by ibilalmohammad8** [comment]
Tried the latest as well as the 4.3.1v but the issue is still there for me. 
![image](https://user-images.githubusercontent.com/57256692/209290445-43f543cf-2227-4adb-a0b3-352bcef0627d.png)

**Comment by DEV-BDM** [comment]
Anybody found solutions for [None of the available transfer modes work]. SamKirkland/FTP-Deploy-Action@4.3.3

![image](https://user-images.githubusercontent.com/121104491/212631418-3776bd99-4236-47a7-9b9e-56187c797eaf.png)

**Comment by inventorDrizzt** [comment]
just update to version 4.6.6 , it works
https://www.npmjs.com/package/basic-ftp/v/4.6.6

**Comment by SamKirkland** [comment]
Had a bug on my side. This should be fixed in `v4.3.4`

**Comment by awaidus** [comment]
Same error with latest 4.3.4.

![image](https://user-images.githubusercontent.com/9782807/229213536-4a67cffd-dff8-4ecc-8fb6-6e5a4c172fd8.png)

**Comment by SamKirkland** [comment]
@awaidus can you post your config?

Looking at your log it appears you're still on a old version (4.3.0)

**Comment by awaidus** [comment]
> @awaidus can you post your config?
> 
> Looking at your log it appears you're still on a old version (4.3.0)

I previously tried with 4.3.4 but still not working so I tried again with some older version as it was working fine before. but now none of any working

**Comment by awaidus** [comment]
one more thing it is also not recognizing " **.ftp-deploy-sync-state.json** " whereas this file is already there. 

![image](https://user-images.githubusercontent.com/9782807/229214876-27ea1c91-909d-4a1b-95a0-7ab3643355b0.png)

**Comment by SamKirkland** [comment]
@awaidus Can you switch back to the latest version `4.3.4` and try excluding files that start with `.` [see readme for how](https://github.com/SamKirkland/FTP-Deploy-Action#exclude-files). You also need to change your `state-name` to a file that does NOT start with `.` [see readme for how](https://github.com/SamKirkland/FTP-Deploy-Action#settings).


What I suspect is happening: Your FTP account does not have access to special files (files that start with `.`) - which is why the upload fails on `.editorconfig` and the script cannot see the `.ftp-deploy-sync-state.json` file

**Comment by awaidus** [comment]
> @awaidus Can you switch back to the latest version `4.3.4` and try excluding files that start with `.` [see readme for how](https://github.com/SamKirkland/FTP-Deploy-Action#exclude-files). You also need to change your `state-name` to a file that does NOT start with `.` [see readme for how](https://github.com/SamKirkland/FTP-Deploy-Action#settings).
> 
> What I suspect is happening: Your FTP account does not have access to special files (files that start with `.`) - which is why the upload fails on `.editorconfig` and the script cannot see the `.ftp-deploy-sync-state.json` file

Thank @SamKirkland  for your muck quicker and needed answer. I have changed my config. 

![image](https://user-images.githubusercontent.com/9782807/229217104-00227b46-6aae-47d3-9716-953e4d33601c.png)

would it be worked ? is config is correct ?

**Comment by SamKirkland** [comment]
`state-name` is relative. So **no need** to re-specify `/public_html/laravel-app/`

```yaml
state-name: ftp-deploy-sync-state.json
```
If you make that change it _should_ work - assuming the problem is limited FTP access.

----

If you want to test your config out you can add
```yaml
dry-run: true
```

`dry-run` will output paths/files that WOULD be uploaded. But doesn't attempt to make the uploads. So its useful for testing what files would be excluded.

**Comment by awaidus** [comment]
> ```yaml
> dry-run: true
> ```

Thank you again. with your help I can manage to exclude all files staring from " . " and test the upload using dry-run. it works. but still it could not recognize **ftp-deploy-sync-state.json**. Well let's see what happened after upload completed as it takes a while. 

![image](https://user-images.githubusercontent.com/9782807/229221518-bb56c1f1-5688-4dff-bffe-14a39ebc148f.png)

**Comment by SamKirkland** [comment]
@awaidus `state-name` only works after the initial sync.

**Comment by SamKirkland** [comment]
@awaidus did the upload work?
After the first upload it should be MUCH faster (only changes will be uploaded going forward)

**Comment by Atahar-Hossain** [comment]
![workflows](https://github.com/SamKirkland/FTP-Deploy-Action/assets/65162473/7b4eaba2-f73b-4b4a-8e93-848f73fec216)

after completing this commit i got success message. But when i am going to cpanel there have all folders without file. That means all folders uploaded to cpanel but folders are empty. Secondly files are not uploading which are with (.) like, package.json.

**Comment by theJohnCode** [comment]
This is still a problem in version 4.3.4

**Comment by Sharifur** [comment]
same problem in version 4.3.4

**Comment by presidonaycs** [comment]
Same Issue with version 4.3.4 I have tried all the solutions above @SamKirkland please help

**Comment by presidonaycs** [comment]
The Error I get

Error: None of the available transfer modes work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.0/dist/index.js:4323:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client._uploadFromStream (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.0/dist/index.js:4011:13)
    at async Client._uploadLocalFile (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.0/dist/index.js:3997:20)
Error: Error: None of the available transfer modes work.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: 📂 Sync files

**Comment by presidonaycs** [comment]
It works fine with dry-run, but nothing shows up on the server, not even the empty folders

**Comment by Sharifur** [comment]
I have solved my problem by downgrade to version 4.1.0

**Comment by presidonaycs** [comment]
@Sharifur I have tried that as well, I have also tried 4.0.0, 4.3.0, non worked

**Comment by Sharifur** [comment]
> @Sharifur I have tried that as well, I have also tried 4.0.0, 4.3.0, non worked

Did you try to change your FTP host url to IP address?
example: ftp.yourftp.com to 123.123.123.123

**Comment by presidonaycs** [comment]
![Screenshot 2023-10-28 174942](https://github.com/SamKirkland/FTP-Deploy-Action/assets/58347843/6c3a6012-6df0-4855-8a83-8d850baa5264)

This is my current configuration

**Comment by presidonaycs** [comment]
@Sharifur I just tried that, still didn't work

**Comment by kcnaiamh** [comment]
@presidonaycs Have you solve the problem? I'm exactly facing same situation.

**Comment by presidonaycs** [comment]
I couldn't solve the problem man...

**Comment by sherz12r** [comment]
same problem tried all above suggestions not worked any update?

**Comment by presidonaycs** [comment]
thanks alot man, i'll try ASAP

**Comment by codeparl** [comment]
setting `dry-run: true`   worked for me

**Comment by RayhanulSumon** [comment]
I am facing the same problem dot (.) file not uploading, what should i do? i am on VPS Cpanel.

**Comment by sherz12r** [comment]
Use following

name: Deploy via SFTP
on:
push:
branches:
- master
jobs:
deploy:
name: Deploy
runs-on: ubuntu-latest
if: github.event_name == 'push'
steps:
- name: Checkout
uses: actions/checkout@v3
with:
fetch-depth: 0
- name: Deploy files via SFTP
uses: pressidium/lftp-mirror-action@v1
with:
# SFTP credentials
host: ${{ secrets.SERVER }}
# port: ${{ secrets.USER_N

**Comment by RayhanulSumon** [comment]
`name: 🚀 Deploy website on push to production
on:
  push:
    branches:
      - production
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD}}
          server-dir: /
          exclude: |
            .editorconfig
            .env
            .env.example
            **/.env.staging
            .gitattributes
            .phpunit.result.cache
            .yarnrc.yml
            **/.gitignore*
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.**
`  This is my yml what still dot file not ignoring

**Comment by RayhanulSumon** [comment]
name: 🚀 Deploy website on push to production
on:
  push:
    branches:
      - production
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD}}
          server-dir: /
          exclude: |
            .editorconfig
            .env
            .env.example
            **/.env.staging
            .gitattributes
            .phpunit.result.cache
            .yarnrc.yml
            **/.gitignore*
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.**
  this is my yml still not working
